/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.FormMessageTagging;

/**
 * Service object for domain model class {@link FormMessageTagging}.
 */
public interface FormMessageTaggingService {

    /**
     * Creates a new FormMessageTagging. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FormMessageTagging if any.
     *
     * @param formMessageTagging Details of the FormMessageTagging to be created; value cannot be null.
     * @return The newly created FormMessageTagging.
     */
	FormMessageTagging create(FormMessageTagging formMessageTagging);


	/**
	 * Returns FormMessageTagging by given id if exists.
	 *
	 * @param formmessagetaggingId The id of the FormMessageTagging to get; value cannot be null.
	 * @return FormMessageTagging associated with the given formmessagetaggingId.
     * @throws EntityNotFoundException If no FormMessageTagging is found.
	 */
	FormMessageTagging getById(Integer formmessagetaggingId) throws EntityNotFoundException;

    /**
	 * Find and return the FormMessageTagging by given id if exists, returns null otherwise.
	 *
	 * @param formmessagetaggingId The id of the FormMessageTagging to get; value cannot be null.
	 * @return FormMessageTagging associated with the given formmessagetaggingId.
	 */
	FormMessageTagging findById(Integer formmessagetaggingId);


	/**
	 * Updates the details of an existing FormMessageTagging. It replaces all fields of the existing FormMessageTagging with the given formMessageTagging.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on FormMessageTagging if any.
     *
	 * @param formMessageTagging The details of the FormMessageTagging to be updated; value cannot be null.
	 * @return The updated FormMessageTagging.
	 * @throws EntityNotFoundException if no FormMessageTagging is found with given input.
	 */
	FormMessageTagging update(FormMessageTagging formMessageTagging) throws EntityNotFoundException;

    /**
	 * Deletes an existing FormMessageTagging with the given id.
	 *
	 * @param formmessagetaggingId The id of the FormMessageTagging to be deleted; value cannot be null.
	 * @return The deleted FormMessageTagging.
	 * @throws EntityNotFoundException if no FormMessageTagging found with the given id.
	 */
	FormMessageTagging delete(Integer formmessagetaggingId) throws EntityNotFoundException;

	/**
	 * Find all FormMessageTaggings matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FormMessageTaggings.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<FormMessageTagging> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all FormMessageTaggings matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FormMessageTaggings.
     *
     * @see Pageable
     * @see Page
	 */
    Page<FormMessageTagging> findAll(String query, Pageable pageable);

    /**
	 * Exports all FormMessageTaggings matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the FormMessageTaggings in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the FormMessageTagging.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

