/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.InspectionOutcomeFee;

/**
 * Service object for domain model class {@link InspectionOutcomeFee}.
 */
public interface InspectionOutcomeFeeService {

    /**
     * Creates a new InspectionOutcomeFee. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on InspectionOutcomeFee if any.
     *
     * @param inspectionOutcomeFee Details of the InspectionOutcomeFee to be created; value cannot be null.
     * @return The newly created InspectionOutcomeFee.
     */
	InspectionOutcomeFee create(InspectionOutcomeFee inspectionOutcomeFee);


	/**
	 * Returns InspectionOutcomeFee by given id if exists.
	 *
	 * @param inspectionoutcomefeeId The id of the InspectionOutcomeFee to get; value cannot be null.
	 * @return InspectionOutcomeFee associated with the given inspectionoutcomefeeId.
     * @throws EntityNotFoundException If no InspectionOutcomeFee is found.
	 */
	InspectionOutcomeFee getById(Integer inspectionoutcomefeeId) throws EntityNotFoundException;

    /**
	 * Find and return the InspectionOutcomeFee by given id if exists, returns null otherwise.
	 *
	 * @param inspectionoutcomefeeId The id of the InspectionOutcomeFee to get; value cannot be null.
	 * @return InspectionOutcomeFee associated with the given inspectionoutcomefeeId.
	 */
	InspectionOutcomeFee findById(Integer inspectionoutcomefeeId);

    /**
	 * Find and return the InspectionOutcomeFee for given inspectOutcomeId  andorderToApply  if exists.
	 *
	 * @param inspectOutcomeId value of inspectOutcomeId; value cannot be null.
	 * @param orderToApply value of orderToApply; value cannot be null.
	 * @return InspectionOutcomeFee associated with the given inputs.
     * @throws EntityNotFoundException if no matching InspectionOutcomeFee found.
	 */
    InspectionOutcomeFee getByInspectOutcomeIdAndOrderToApply(Integer inspectOutcomeId, Integer orderToApply)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing InspectionOutcomeFee. It replaces all fields of the existing InspectionOutcomeFee with the given inspectionOutcomeFee.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on InspectionOutcomeFee if any.
     *
	 * @param inspectionOutcomeFee The details of the InspectionOutcomeFee to be updated; value cannot be null.
	 * @return The updated InspectionOutcomeFee.
	 * @throws EntityNotFoundException if no InspectionOutcomeFee is found with given input.
	 */
	InspectionOutcomeFee update(InspectionOutcomeFee inspectionOutcomeFee) throws EntityNotFoundException;

    /**
	 * Deletes an existing InspectionOutcomeFee with the given id.
	 *
	 * @param inspectionoutcomefeeId The id of the InspectionOutcomeFee to be deleted; value cannot be null.
	 * @return The deleted InspectionOutcomeFee.
	 * @throws EntityNotFoundException if no InspectionOutcomeFee found with the given id.
	 */
	InspectionOutcomeFee delete(Integer inspectionoutcomefeeId) throws EntityNotFoundException;

	/**
	 * Find all InspectionOutcomeFees matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching InspectionOutcomeFees.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<InspectionOutcomeFee> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all InspectionOutcomeFees matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching InspectionOutcomeFees.
     *
     * @see Pageable
     * @see Page
	 */
    Page<InspectionOutcomeFee> findAll(String query, Pageable pageable);

    /**
	 * Exports all InspectionOutcomeFees matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the InspectionOutcomeFees in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the InspectionOutcomeFee.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

