/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.LetterSection;


/**
 * ServiceImpl object for domain model class LetterSection.
 *
 * @see LetterSection
 */
@Service("cx2.LetterSectionService")
public class LetterSectionServiceImpl implements LetterSectionService {

    private static final Logger LOGGER = LoggerFactory.getLogger(LetterSectionServiceImpl.class);


    @Autowired
    @Qualifier("cx2.LetterSectionDao")
    private WMGenericDao<LetterSection, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<LetterSection, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "cx2TransactionManager")
    @Override
	public LetterSection create(LetterSection letterSection) {
        LOGGER.debug("Creating a new LetterSection with information: {}", letterSection);
        LetterSection letterSectionCreated = this.wmGenericDao.create(letterSection);
        return letterSectionCreated;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public LetterSection getById(Integer lettersectionId) throws EntityNotFoundException {
        LOGGER.debug("Finding LetterSection by id: {}", lettersectionId);
        LetterSection letterSection = this.wmGenericDao.findById(lettersectionId);
        if (letterSection == null){
            LOGGER.debug("No LetterSection found with id: {}", lettersectionId);
            throw new EntityNotFoundException(String.valueOf(lettersectionId));
        }
        return letterSection;
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public LetterSection findById(Integer lettersectionId) {
        LOGGER.debug("Finding LetterSection by id: {}", lettersectionId);
        return this.wmGenericDao.findById(lettersectionId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "cx2TransactionManager")
	@Override
	public LetterSection update(LetterSection letterSection) throws EntityNotFoundException {
        LOGGER.debug("Updating LetterSection with information: {}", letterSection);
        this.wmGenericDao.update(letterSection);

        Integer lettersectionId = letterSection.getId();

        return this.wmGenericDao.findById(lettersectionId);
    }

    @Transactional(value = "cx2TransactionManager")
	@Override
	public LetterSection delete(Integer lettersectionId) throws EntityNotFoundException {
        LOGGER.debug("Deleting LetterSection with id: {}", lettersectionId);
        LetterSection deleted = this.wmGenericDao.findById(lettersectionId);
        if (deleted == null) {
            LOGGER.debug("No LetterSection found with id: {}", lettersectionId);
            throw new EntityNotFoundException(String.valueOf(lettersectionId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Page<LetterSection> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all LetterSections");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<LetterSection> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all LetterSections");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service cx2 for table LetterSection to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

