/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.MasterProjects;

/**
 * Service object for domain model class {@link MasterProjects}.
 */
public interface MasterProjectsService {

    /**
     * Creates a new MasterProjects. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on MasterProjects if any.
     *
     * @param masterProjects Details of the MasterProjects to be created; value cannot be null.
     * @return The newly created MasterProjects.
     */
	MasterProjects create(MasterProjects masterProjects);


	/**
	 * Returns MasterProjects by given id if exists.
	 *
	 * @param masterprojectsId The id of the MasterProjects to get; value cannot be null.
	 * @return MasterProjects associated with the given masterprojectsId.
     * @throws EntityNotFoundException If no MasterProjects is found.
	 */
	MasterProjects getById(Integer masterprojectsId) throws EntityNotFoundException;

    /**
	 * Find and return the MasterProjects by given id if exists, returns null otherwise.
	 *
	 * @param masterprojectsId The id of the MasterProjects to get; value cannot be null.
	 * @return MasterProjects associated with the given masterprojectsId.
	 */
	MasterProjects findById(Integer masterprojectsId);


	/**
	 * Updates the details of an existing MasterProjects. It replaces all fields of the existing MasterProjects with the given masterProjects.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on MasterProjects if any.
     *
	 * @param masterProjects The details of the MasterProjects to be updated; value cannot be null.
	 * @return The updated MasterProjects.
	 * @throws EntityNotFoundException if no MasterProjects is found with given input.
	 */
	MasterProjects update(MasterProjects masterProjects) throws EntityNotFoundException;

    /**
	 * Deletes an existing MasterProjects with the given id.
	 *
	 * @param masterprojectsId The id of the MasterProjects to be deleted; value cannot be null.
	 * @return The deleted MasterProjects.
	 * @throws EntityNotFoundException if no MasterProjects found with the given id.
	 */
	MasterProjects delete(Integer masterprojectsId) throws EntityNotFoundException;

	/**
	 * Find all MasterProjects matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching MasterProjects.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<MasterProjects> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all MasterProjects matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching MasterProjects.
     *
     * @see Pageable
     * @see Page
	 */
    Page<MasterProjects> findAll(String query, Pageable pageable);

    /**
	 * Exports all MasterProjects matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the MasterProjects in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the MasterProjects.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

