/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.Table291;


/**
 * ServiceImpl object for domain model class Table291.
 *
 * @see Table291
 */
@Service("cx2.Table291Service")
public class Table291ServiceImpl implements Table291Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(Table291ServiceImpl.class);


    @Autowired
    @Qualifier("cx2.Table291Dao")
    private WMGenericDao<Table291, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Table291, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "cx2TransactionManager")
    @Override
	public Table291 create(Table291 table291) {
        LOGGER.debug("Creating a new Table291 with information: {}", table291);
        Table291 table291Created = this.wmGenericDao.create(table291);
        return table291Created;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Table291 getById(Integer table291Id) throws EntityNotFoundException {
        LOGGER.debug("Finding Table291 by id: {}", table291Id);
        Table291 table291 = this.wmGenericDao.findById(table291Id);
        if (table291 == null){
            LOGGER.debug("No Table291 found with id: {}", table291Id);
            throw new EntityNotFoundException(String.valueOf(table291Id));
        }
        return table291;
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Table291 findById(Integer table291Id) {
        LOGGER.debug("Finding Table291 by id: {}", table291Id);
        return this.wmGenericDao.findById(table291Id);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "cx2TransactionManager")
	@Override
	public Table291 update(Table291 table291) throws EntityNotFoundException {
        LOGGER.debug("Updating Table291 with information: {}", table291);
        this.wmGenericDao.update(table291);

        Integer table291Id = table291.getId();

        return this.wmGenericDao.findById(table291Id);
    }

    @Transactional(value = "cx2TransactionManager")
	@Override
	public Table291 delete(Integer table291Id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Table291 with id: {}", table291Id);
        Table291 deleted = this.wmGenericDao.findById(table291Id);
        if (deleted == null) {
            LOGGER.debug("No Table291 found with id: {}", table291Id);
            throw new EntityNotFoundException(String.valueOf(table291Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Page<Table291> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Table291s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Table291> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Table291s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service cx2 for table Table291 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }



}

