/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.Table291;

/**
 * Service object for domain model class {@link Table291}.
 */
public interface Table291Service {

    /**
     * Creates a new Table291. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table291 if any.
     *
     * @param table291 Details of the Table291 to be created; value cannot be null.
     * @return The newly created Table291.
     */
	Table291 create(Table291 table291);


	/**
	 * Returns Table291 by given id if exists.
	 *
	 * @param table291Id The id of the Table291 to get; value cannot be null.
	 * @return Table291 associated with the given table291Id.
     * @throws EntityNotFoundException If no Table291 is found.
	 */
	Table291 getById(Integer table291Id) throws EntityNotFoundException;

    /**
	 * Find and return the Table291 by given id if exists, returns null otherwise.
	 *
	 * @param table291Id The id of the Table291 to get; value cannot be null.
	 * @return Table291 associated with the given table291Id.
	 */
	Table291 findById(Integer table291Id);


	/**
	 * Updates the details of an existing Table291. It replaces all fields of the existing Table291 with the given table291.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Table291 if any.
     *
	 * @param table291 The details of the Table291 to be updated; value cannot be null.
	 * @return The updated Table291.
	 * @throws EntityNotFoundException if no Table291 is found with given input.
	 */
	Table291 update(Table291 table291) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table291 with the given id.
	 *
	 * @param table291Id The id of the Table291 to be deleted; value cannot be null.
	 * @return The deleted Table291.
	 * @throws EntityNotFoundException if no Table291 found with the given id.
	 */
	Table291 delete(Integer table291Id) throws EntityNotFoundException;

	/**
	 * Find all Table291s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table291s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Table291> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Table291s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table291s.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Table291> findAll(String query, Pageable pageable);

    /**
	 * Exports all Table291s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table291s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Table291.
	 */
	long count(String query);


}

