/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.Fees;
import com.civicxpress.cx2.FormHistory;
import com.civicxpress.cx2.FormMessageTagging;
import com.civicxpress.cx2.FormMessages;
import com.civicxpress.cx2.FormsToInspections;
import com.civicxpress.cx2.Gis2forms;
import com.civicxpress.cx2.InspectionDesign;
import com.civicxpress.cx2.InspectionGis;
import com.civicxpress.cx2.MasterCases;
import com.civicxpress.cx2.MasterForms;
import com.civicxpress.cx2.MasterInspections;
import com.civicxpress.cx2.MunicipalityGroupMembers;
import com.civicxpress.cx2.MyCart;
import com.civicxpress.cx2.ProjectForms;
import com.civicxpress.cx2.ProjectGisrecords;
import com.civicxpress.cx2.ProjectSharedWith;
import com.civicxpress.cx2.ProjectTasks;
import com.civicxpress.cx2.Projects;
import com.civicxpress.cx2.Roles;
import com.civicxpress.cx2.SharedWith;
import com.civicxpress.cx2.UserPasswordResetTokens;
import com.civicxpress.cx2.UserSubscriptions;
import com.civicxpress.cx2.UserViewPreferences;
import com.civicxpress.cx2.Users;
import com.civicxpress.cx2.VendorAdmins;
import com.civicxpress.cx2.VendorUsers;


/**
 * ServiceImpl object for domain model class Users.
 *
 * @see Users
 */
@Service("cx2.UsersService")
public class UsersServiceImpl implements UsersService {

    private static final Logger LOGGER = LoggerFactory.getLogger(UsersServiceImpl.class);

    @Autowired
	@Qualifier("cx2.FormsToInspectionsService")
	private FormsToInspectionsService formsToInspectionsService;

    @Autowired
	@Qualifier("cx2.FormMessageTaggingService")
	private FormMessageTaggingService formMessageTaggingService;

    @Autowired
	@Qualifier("cx2.MasterCasesService")
	private MasterCasesService masterCasesService;

    @Autowired
	@Qualifier("cx2.MyCartService")
	private MyCartService myCartService;

    @Autowired
	@Qualifier("cx2.ProjectTasksService")
	private ProjectTasksService projectTasksService;

    @Autowired
	@Qualifier("cx2.MasterFormsService")
	private MasterFormsService masterFormsService;

    @Autowired
	@Qualifier("cx2.InspectionGisService")
	private InspectionGisService inspectionGisService;

    @Autowired
	@Qualifier("cx2.MasterInspectionsService")
	private MasterInspectionsService masterInspectionsService;

    @Autowired
	@Qualifier("cx2.VendorUsersService")
	private VendorUsersService vendorUsersService;

    @Autowired
	@Qualifier("cx2.MunicipalityGroupMembersService")
	private MunicipalityGroupMembersService municipalityGroupMembersService;

    @Autowired
	@Qualifier("cx2.Gis2formsService")
	private Gis2formsService gis2formsService;

    @Autowired
	@Qualifier("cx2.FormMessagesService")
	private FormMessagesService formMessagesService;

    @Autowired
	@Qualifier("cx2.InspectionDesignService")
	private InspectionDesignService inspectionDesignService;

    @Autowired
	@Qualifier("cx2.ProjectGisrecordsService")
	private ProjectGisrecordsService projectGisrecordsService;

    @Autowired
	@Qualifier("cx2.SharedWithService")
	private SharedWithService sharedWithService;

    @Autowired
	@Qualifier("cx2.ProjectFormsService")
	private ProjectFormsService projectFormsService;

    @Autowired
	@Qualifier("cx2.ProjectsService")
	private ProjectsService projectsService;

    @Autowired
	@Qualifier("cx2.FormHistoryService")
	private FormHistoryService formHistoryService;

    @Autowired
	@Qualifier("cx2.FeesService")
	private FeesService feesService;

    @Autowired
	@Qualifier("cx2.UserPasswordResetTokensService")
	private UserPasswordResetTokensService userPasswordResetTokensService;

    @Autowired
	@Qualifier("cx2.ProjectSharedWithService")
	private ProjectSharedWithService projectSharedWithService;

    @Autowired
	@Qualifier("cx2.RolesService")
	private RolesService rolesService;

    @Autowired
	@Qualifier("cx2.UserViewPreferencesService")
	private UserViewPreferencesService userViewPreferencesService;

    @Autowired
	@Qualifier("cx2.VendorAdminsService")
	private VendorAdminsService vendorAdminsService;

    @Autowired
	@Qualifier("cx2.UserSubscriptionsService")
	private UserSubscriptionsService userSubscriptionsService;

    @Autowired
    @Qualifier("cx2.UsersDao")
    private WMGenericDao<Users, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Users, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "cx2TransactionManager")
    @Override
	public Users create(Users users) {
        LOGGER.debug("Creating a new Users with information: {}", users);
        Users usersCreated = this.wmGenericDao.create(users);
        if(usersCreated.getFeeses() != null) {
            for(Fees feese : usersCreated.getFeeses()) {
                feese.setUsers(usersCreated);
                LOGGER.debug("Creating a new child Fees with information: {}", feese);
                feesService.create(feese);
            }
        }

        if(usersCreated.getFormHistories() != null) {
            for(FormHistory formHistorie : usersCreated.getFormHistories()) {
                formHistorie.setUsers(usersCreated);
                LOGGER.debug("Creating a new child FormHistory with information: {}", formHistorie);
                formHistoryService.create(formHistorie);
            }
        }

        if(usersCreated.getFormMessageses() != null) {
            for(FormMessages formMessagese : usersCreated.getFormMessageses()) {
                formMessagese.setUsers(usersCreated);
                LOGGER.debug("Creating a new child FormMessages with information: {}", formMessagese);
                formMessagesService.create(formMessagese);
            }
        }

        if(usersCreated.getFormMessageTaggings() != null) {
            for(FormMessageTagging formMessageTagging : usersCreated.getFormMessageTaggings()) {
                formMessageTagging.setUsers(usersCreated);
                LOGGER.debug("Creating a new child FormMessageTagging with information: {}", formMessageTagging);
                formMessageTaggingService.create(formMessageTagging);
            }
        }

        if(usersCreated.getFormsToInspectionses() != null) {
            for(FormsToInspections formsToInspectionse : usersCreated.getFormsToInspectionses()) {
                formsToInspectionse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child FormsToInspections with information: {}", formsToInspectionse);
                formsToInspectionsService.create(formsToInspectionse);
            }
        }

        if(usersCreated.getInspectionDesigns() != null) {
            for(InspectionDesign inspectionDesign : usersCreated.getInspectionDesigns()) {
                inspectionDesign.setUsers(usersCreated);
                LOGGER.debug("Creating a new child InspectionDesign with information: {}", inspectionDesign);
                inspectionDesignService.create(inspectionDesign);
            }
        }

        if(usersCreated.getGis2formses() != null) {
            for(Gis2forms gis2formse : usersCreated.getGis2formses()) {
                gis2formse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child Gis2forms with information: {}", gis2formse);
                gis2formsService.create(gis2formse);
            }
        }

        if(usersCreated.getInspectionGises() != null) {
            for(InspectionGis inspectionGise : usersCreated.getInspectionGises()) {
                inspectionGise.setUsers(usersCreated);
                LOGGER.debug("Creating a new child InspectionGis with information: {}", inspectionGise);
                inspectionGisService.create(inspectionGise);
            }
        }

        if(usersCreated.getMasterFormses() != null) {
            for(MasterForms masterFormse : usersCreated.getMasterFormses()) {
                masterFormse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child MasterForms with information: {}", masterFormse);
                masterFormsService.create(masterFormse);
            }
        }

        if(usersCreated.getMasterCasesesForCreatedBy() != null) {
            for(MasterCases masterCasesesForCreatedBy : usersCreated.getMasterCasesesForCreatedBy()) {
                masterCasesesForCreatedBy.setUsersByCreatedBy(usersCreated);
                LOGGER.debug("Creating a new child MasterCases with information: {}", masterCasesesForCreatedBy);
                masterCasesService.create(masterCasesesForCreatedBy);
            }
        }

        if(usersCreated.getMasterCasesesForModifiedBy() != null) {
            for(MasterCases masterCasesesForModifiedBy : usersCreated.getMasterCasesesForModifiedBy()) {
                masterCasesesForModifiedBy.setUsersByModifiedBy(usersCreated);
                LOGGER.debug("Creating a new child MasterCases with information: {}", masterCasesesForModifiedBy);
                masterCasesService.create(masterCasesesForModifiedBy);
            }
        }

        if(usersCreated.getMasterInspectionsesForAssignedTo() != null) {
            for(MasterInspections masterInspectionsesForAssignedTo : usersCreated.getMasterInspectionsesForAssignedTo()) {
                masterInspectionsesForAssignedTo.setUsersByAssignedTo(usersCreated);
                LOGGER.debug("Creating a new child MasterInspections with information: {}", masterInspectionsesForAssignedTo);
                masterInspectionsService.create(masterInspectionsesForAssignedTo);
            }
        }

        if(usersCreated.getMasterInspectionsesForRequestedBy() != null) {
            for(MasterInspections masterInspectionsesForRequestedBy : usersCreated.getMasterInspectionsesForRequestedBy()) {
                masterInspectionsesForRequestedBy.setUsersByRequestedBy(usersCreated);
                LOGGER.debug("Creating a new child MasterInspections with information: {}", masterInspectionsesForRequestedBy);
                masterInspectionsService.create(masterInspectionsesForRequestedBy);
            }
        }

        if(usersCreated.getMasterInspectionsesForModifiedBy() != null) {
            for(MasterInspections masterInspectionsesForModifiedBy : usersCreated.getMasterInspectionsesForModifiedBy()) {
                masterInspectionsesForModifiedBy.setUsersByModifiedBy(usersCreated);
                LOGGER.debug("Creating a new child MasterInspections with information: {}", masterInspectionsesForModifiedBy);
                masterInspectionsService.create(masterInspectionsesForModifiedBy);
            }
        }

        if(usersCreated.getMunicipalityGroupMemberses() != null) {
            for(MunicipalityGroupMembers municipalityGroupMemberse : usersCreated.getMunicipalityGroupMemberses()) {
                municipalityGroupMemberse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child MunicipalityGroupMembers with information: {}", municipalityGroupMemberse);
                municipalityGroupMembersService.create(municipalityGroupMemberse);
            }
        }

        if(usersCreated.getProjectFormses() != null) {
            for(ProjectForms projectFormse : usersCreated.getProjectFormses()) {
                projectFormse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child ProjectForms with information: {}", projectFormse);
                projectFormsService.create(projectFormse);
            }
        }

        if(usersCreated.getProjectsesForCreatedBy() != null) {
            for(Projects projectsesForCreatedBy : usersCreated.getProjectsesForCreatedBy()) {
                projectsesForCreatedBy.setUsersByCreatedBy(usersCreated);
                LOGGER.debug("Creating a new child Projects with information: {}", projectsesForCreatedBy);
                projectsService.create(projectsesForCreatedBy);
            }
        }

        if(usersCreated.getProjectsesForModifiedBy() != null) {
            for(Projects projectsesForModifiedBy : usersCreated.getProjectsesForModifiedBy()) {
                projectsesForModifiedBy.setUsersByModifiedBy(usersCreated);
                LOGGER.debug("Creating a new child Projects with information: {}", projectsesForModifiedBy);
                projectsService.create(projectsesForModifiedBy);
            }
        }

        if(usersCreated.getProjectGisrecordses() != null) {
            for(ProjectGisrecords projectGisrecordse : usersCreated.getProjectGisrecordses()) {
                projectGisrecordse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child ProjectGisrecords with information: {}", projectGisrecordse);
                projectGisrecordsService.create(projectGisrecordse);
            }
        }

        if(usersCreated.getProjectSharedWithsForProjectSharedBy() != null) {
            for(ProjectSharedWith projectSharedWithsForProjectSharedBy : usersCreated.getProjectSharedWithsForProjectSharedBy()) {
                projectSharedWithsForProjectSharedBy.setUsersByProjectSharedBy(usersCreated);
                LOGGER.debug("Creating a new child ProjectSharedWith with information: {}", projectSharedWithsForProjectSharedBy);
                projectSharedWithService.create(projectSharedWithsForProjectSharedBy);
            }
        }

        if(usersCreated.getProjectSharedWithsForProjectSharedWithUser() != null) {
            for(ProjectSharedWith projectSharedWithsForProjectSharedWithUser : usersCreated.getProjectSharedWithsForProjectSharedWithUser()) {
                projectSharedWithsForProjectSharedWithUser.setUsersByProjectSharedWithUser(usersCreated);
                LOGGER.debug("Creating a new child ProjectSharedWith with information: {}", projectSharedWithsForProjectSharedWithUser);
                projectSharedWithService.create(projectSharedWithsForProjectSharedWithUser);
            }
        }

        if(usersCreated.getProjectTasksesForAssignedTo() != null) {
            for(ProjectTasks projectTasksesForAssignedTo : usersCreated.getProjectTasksesForAssignedTo()) {
                projectTasksesForAssignedTo.setUsersByAssignedTo(usersCreated);
                LOGGER.debug("Creating a new child ProjectTasks with information: {}", projectTasksesForAssignedTo);
                projectTasksService.create(projectTasksesForAssignedTo);
            }
        }

        if(usersCreated.getProjectTasksesForCreatedBy() != null) {
            for(ProjectTasks projectTasksesForCreatedBy : usersCreated.getProjectTasksesForCreatedBy()) {
                projectTasksesForCreatedBy.setUsersByCreatedBy(usersCreated);
                LOGGER.debug("Creating a new child ProjectTasks with information: {}", projectTasksesForCreatedBy);
                projectTasksService.create(projectTasksesForCreatedBy);
            }
        }

        if(usersCreated.getRoleses() != null) {
            for(Roles rolese : usersCreated.getRoleses()) {
                rolese.setUsers(usersCreated);
                LOGGER.debug("Creating a new child Roles with information: {}", rolese);
                rolesService.create(rolese);
            }
        }

        if(usersCreated.getSharedWithsForCreatedBy() != null) {
            for(SharedWith sharedWithsForCreatedBy : usersCreated.getSharedWithsForCreatedBy()) {
                sharedWithsForCreatedBy.setUsersByCreatedBy(usersCreated);
                LOGGER.debug("Creating a new child SharedWith with information: {}", sharedWithsForCreatedBy);
                sharedWithService.create(sharedWithsForCreatedBy);
            }
        }

        if(usersCreated.getSharedWithsForSharedWithUser() != null) {
            for(SharedWith sharedWithsForSharedWithUser : usersCreated.getSharedWithsForSharedWithUser()) {
                sharedWithsForSharedWithUser.setUsersBySharedWithUser(usersCreated);
                LOGGER.debug("Creating a new child SharedWith with information: {}", sharedWithsForSharedWithUser);
                sharedWithService.create(sharedWithsForSharedWithUser);
            }
        }

        if(usersCreated.getMyCarts() != null) {
            for(MyCart myCart : usersCreated.getMyCarts()) {
                myCart.setUsers(usersCreated);
                LOGGER.debug("Creating a new child MyCart with information: {}", myCart);
                myCartService.create(myCart);
            }
        }

        if(usersCreated.getUserPasswordResetTokenses() != null) {
            for(UserPasswordResetTokens userPasswordResetTokense : usersCreated.getUserPasswordResetTokenses()) {
                userPasswordResetTokense.setUsers(usersCreated);
                LOGGER.debug("Creating a new child UserPasswordResetTokens with information: {}", userPasswordResetTokense);
                userPasswordResetTokensService.create(userPasswordResetTokense);
            }
        }

        if(usersCreated.getUserSubscriptionses() != null) {
            for(UserSubscriptions userSubscriptionse : usersCreated.getUserSubscriptionses()) {
                userSubscriptionse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child UserSubscriptions with information: {}", userSubscriptionse);
                userSubscriptionsService.create(userSubscriptionse);
            }
        }

        if(usersCreated.getUserViewPreferenceses() != null) {
            for(UserViewPreferences userViewPreferencese : usersCreated.getUserViewPreferenceses()) {
                userViewPreferencese.setUsers(usersCreated);
                LOGGER.debug("Creating a new child UserViewPreferences with information: {}", userViewPreferencese);
                userViewPreferencesService.create(userViewPreferencese);
            }
        }

        if(usersCreated.getVendorAdminses() != null) {
            for(VendorAdmins vendorAdminse : usersCreated.getVendorAdminses()) {
                vendorAdminse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child VendorAdmins with information: {}", vendorAdminse);
                vendorAdminsService.create(vendorAdminse);
            }
        }

        if(usersCreated.getVendorUserses() != null) {
            for(VendorUsers vendorUserse : usersCreated.getVendorUserses()) {
                vendorUserse.setUsers(usersCreated);
                LOGGER.debug("Creating a new child VendorUsers with information: {}", vendorUserse);
                vendorUsersService.create(vendorUserse);
            }
        }
        return usersCreated;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Users getById(Integer usersId) throws EntityNotFoundException {
        LOGGER.debug("Finding Users by id: {}", usersId);
        Users users = this.wmGenericDao.findById(usersId);
        if (users == null){
            LOGGER.debug("No Users found with id: {}", usersId);
            throw new EntityNotFoundException(String.valueOf(usersId));
        }
        return users;
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Users findById(Integer usersId) {
        LOGGER.debug("Finding Users by id: {}", usersId);
        return this.wmGenericDao.findById(usersId);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Users getByEmail(String email) {
        Map<String, Object> emailMap = new HashMap<>();
        emailMap.put("email", email);

        LOGGER.debug("Finding Users by unique keys: {}", emailMap);
        Users users = this.wmGenericDao.findByUniqueKey(emailMap);

        if (users == null){
            LOGGER.debug("No Users found with given unique key values: {}", emailMap);
            throw new EntityNotFoundException(String.valueOf(emailMap));
        }

        return users;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "cx2TransactionManager")
	@Override
	public Users update(Users users) throws EntityNotFoundException {
        LOGGER.debug("Updating Users with information: {}", users);
        this.wmGenericDao.update(users);

        Integer usersId = users.getId();

        return this.wmGenericDao.findById(usersId);
    }

    @Transactional(value = "cx2TransactionManager")
	@Override
	public Users delete(Integer usersId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Users with id: {}", usersId);
        Users deleted = this.wmGenericDao.findById(usersId);
        if (deleted == null) {
            LOGGER.debug("No Users found with id: {}", usersId);
            throw new EntityNotFoundException(String.valueOf(usersId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Page<Users> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Users");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Users> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Users");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service cx2 for table Users to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Fees> findAssociatedFeeses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated feeses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return feesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<FormHistory> findAssociatedFormHistories(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated formHistories");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return formHistoryService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<FormMessages> findAssociatedFormMessageses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated formMessageses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return formMessagesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<FormMessageTagging> findAssociatedFormMessageTaggings(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated formMessageTaggings");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return formMessageTaggingService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<FormsToInspections> findAssociatedFormsToInspectionses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated formsToInspectionses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return formsToInspectionsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<InspectionDesign> findAssociatedInspectionDesigns(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated inspectionDesigns");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return inspectionDesignService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Gis2forms> findAssociatedGis2formses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated gis2formses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return gis2formsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<InspectionGis> findAssociatedInspectionGises(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated inspectionGises");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return inspectionGisService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterForms> findAssociatedMasterFormses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterFormses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return masterFormsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterCases> findAssociatedMasterCasesesForCreatedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterCasesesForCreatedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByCreatedBy.id = '" + id + "'");

        return masterCasesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterCases> findAssociatedMasterCasesesForModifiedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterCasesesForModifiedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByModifiedBy.id = '" + id + "'");

        return masterCasesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterInspections> findAssociatedMasterInspectionsesForAssignedTo(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterInspectionsesForAssignedTo");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByAssignedTo.id = '" + id + "'");

        return masterInspectionsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterInspections> findAssociatedMasterInspectionsesForRequestedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterInspectionsesForRequestedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByRequestedBy.id = '" + id + "'");

        return masterInspectionsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MasterInspections> findAssociatedMasterInspectionsesForModifiedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated masterInspectionsesForModifiedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByModifiedBy.id = '" + id + "'");

        return masterInspectionsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MunicipalityGroupMembers> findAssociatedMunicipalityGroupMemberses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated municipalityGroupMemberses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return municipalityGroupMembersService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectForms> findAssociatedProjectFormses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectFormses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return projectFormsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Projects> findAssociatedProjectsesForCreatedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectsesForCreatedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByCreatedBy.id = '" + id + "'");

        return projectsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Projects> findAssociatedProjectsesForModifiedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectsesForModifiedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByModifiedBy.id = '" + id + "'");

        return projectsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectGisrecords> findAssociatedProjectGisrecordses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectGisrecordses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return projectGisrecordsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectSharedWith> findAssociatedProjectSharedWithsForProjectSharedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectSharedWithsForProjectSharedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByProjectSharedBy.id = '" + id + "'");

        return projectSharedWithService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectSharedWith> findAssociatedProjectSharedWithsForProjectSharedWithUser(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectSharedWithsForProjectSharedWithUser");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByProjectSharedWithUser.id = '" + id + "'");

        return projectSharedWithService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectTasks> findAssociatedProjectTasksesForAssignedTo(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectTasksesForAssignedTo");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByAssignedTo.id = '" + id + "'");

        return projectTasksService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<ProjectTasks> findAssociatedProjectTasksesForCreatedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated projectTasksesForCreatedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByCreatedBy.id = '" + id + "'");

        return projectTasksService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Roles> findAssociatedRoleses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated roleses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return rolesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<SharedWith> findAssociatedSharedWithsForCreatedBy(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated sharedWithsForCreatedBy");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersByCreatedBy.id = '" + id + "'");

        return sharedWithService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<SharedWith> findAssociatedSharedWithsForSharedWithUser(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated sharedWithsForSharedWithUser");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("usersBySharedWithUser.id = '" + id + "'");

        return sharedWithService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<MyCart> findAssociatedMyCarts(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated myCarts");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return myCartService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<UserPasswordResetTokens> findAssociatedUserPasswordResetTokenses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated userPasswordResetTokenses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return userPasswordResetTokensService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<UserSubscriptions> findAssociatedUserSubscriptionses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated userSubscriptionses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return userSubscriptionsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<UserViewPreferences> findAssociatedUserViewPreferenceses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated userViewPreferenceses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return userViewPreferencesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<VendorAdmins> findAssociatedVendorAdminses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated vendorAdminses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return vendorAdminsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<VendorUsers> findAssociatedVendorUserses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated vendorUserses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("users.id = '" + id + "'");

        return vendorUsersService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service FormsToInspectionsService instance
	 */
	protected void setFormsToInspectionsService(FormsToInspectionsService service) {
        this.formsToInspectionsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service FormMessageTaggingService instance
	 */
	protected void setFormMessageTaggingService(FormMessageTaggingService service) {
        this.formMessageTaggingService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service MasterCasesService instance
	 */
	protected void setMasterCasesService(MasterCasesService service) {
        this.masterCasesService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service MyCartService instance
	 */
	protected void setMyCartService(MyCartService service) {
        this.myCartService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ProjectTasksService instance
	 */
	protected void setProjectTasksService(ProjectTasksService service) {
        this.projectTasksService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service MasterFormsService instance
	 */
	protected void setMasterFormsService(MasterFormsService service) {
        this.masterFormsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service InspectionGisService instance
	 */
	protected void setInspectionGisService(InspectionGisService service) {
        this.inspectionGisService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service MasterInspectionsService instance
	 */
	protected void setMasterInspectionsService(MasterInspectionsService service) {
        this.masterInspectionsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service VendorUsersService instance
	 */
	protected void setVendorUsersService(VendorUsersService service) {
        this.vendorUsersService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service MunicipalityGroupMembersService instance
	 */
	protected void setMunicipalityGroupMembersService(MunicipalityGroupMembersService service) {
        this.municipalityGroupMembersService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service Gis2formsService instance
	 */
	protected void setGis2formsService(Gis2formsService service) {
        this.gis2formsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service FormMessagesService instance
	 */
	protected void setFormMessagesService(FormMessagesService service) {
        this.formMessagesService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service InspectionDesignService instance
	 */
	protected void setInspectionDesignService(InspectionDesignService service) {
        this.inspectionDesignService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ProjectGisrecordsService instance
	 */
	protected void setProjectGisrecordsService(ProjectGisrecordsService service) {
        this.projectGisrecordsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service SharedWithService instance
	 */
	protected void setSharedWithService(SharedWithService service) {
        this.sharedWithService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ProjectFormsService instance
	 */
	protected void setProjectFormsService(ProjectFormsService service) {
        this.projectFormsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ProjectsService instance
	 */
	protected void setProjectsService(ProjectsService service) {
        this.projectsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service FormHistoryService instance
	 */
	protected void setFormHistoryService(FormHistoryService service) {
        this.formHistoryService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service FeesService instance
	 */
	protected void setFeesService(FeesService service) {
        this.feesService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserPasswordResetTokensService instance
	 */
	protected void setUserPasswordResetTokensService(UserPasswordResetTokensService service) {
        this.userPasswordResetTokensService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ProjectSharedWithService instance
	 */
	protected void setProjectSharedWithService(ProjectSharedWithService service) {
        this.projectSharedWithService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service RolesService instance
	 */
	protected void setRolesService(RolesService service) {
        this.rolesService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserViewPreferencesService instance
	 */
	protected void setUserViewPreferencesService(UserViewPreferencesService service) {
        this.userViewPreferencesService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service VendorAdminsService instance
	 */
	protected void setVendorAdminsService(VendorAdminsService service) {
        this.vendorAdminsService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserSubscriptionsService instance
	 */
	protected void setUserSubscriptionsService(UserSubscriptionsService service) {
        this.userSubscriptionsService = service;
    }

}

