/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.Vendors2form;


/**
 * ServiceImpl object for domain model class Vendors2form.
 *
 * @see Vendors2form
 */
@Service("cx2.Vendors2formService")
public class Vendors2formServiceImpl implements Vendors2formService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Vendors2formServiceImpl.class);


    @Autowired
    @Qualifier("cx2.Vendors2formDao")
    private WMGenericDao<Vendors2form, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Vendors2form, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "cx2TransactionManager")
    @Override
	public Vendors2form create(Vendors2form vendors2form) {
        LOGGER.debug("Creating a new Vendors2form with information: {}", vendors2form);
        Vendors2form vendors2formCreated = this.wmGenericDao.create(vendors2form);
        return vendors2formCreated;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Vendors2form getById(Integer vendors2formId) throws EntityNotFoundException {
        LOGGER.debug("Finding Vendors2form by id: {}", vendors2formId);
        Vendors2form vendors2form = this.wmGenericDao.findById(vendors2formId);
        if (vendors2form == null){
            LOGGER.debug("No Vendors2form found with id: {}", vendors2formId);
            throw new EntityNotFoundException(String.valueOf(vendors2formId));
        }
        return vendors2form;
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Vendors2form findById(Integer vendors2formId) {
        LOGGER.debug("Finding Vendors2form by id: {}", vendors2formId);
        return this.wmGenericDao.findById(vendors2formId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "cx2TransactionManager")
	@Override
	public Vendors2form update(Vendors2form vendors2form) throws EntityNotFoundException {
        LOGGER.debug("Updating Vendors2form with information: {}", vendors2form);
        this.wmGenericDao.update(vendors2form);

        Integer vendors2formId = vendors2form.getId();

        return this.wmGenericDao.findById(vendors2formId);
    }

    @Transactional(value = "cx2TransactionManager")
	@Override
	public Vendors2form delete(Integer vendors2formId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Vendors2form with id: {}", vendors2formId);
        Vendors2form deleted = this.wmGenericDao.findById(vendors2formId);
        if (deleted == null) {
            LOGGER.debug("No Vendors2form found with id: {}", vendors2formId);
            throw new EntityNotFoundException(String.valueOf(vendors2formId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public Page<Vendors2form> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Vendors2forms");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Page<Vendors2form> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Vendors2forms");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service cx2 for table Vendors2form to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "cx2TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

