/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.civicxpress.cx2.Vendors2form;

/**
 * Service object for domain model class {@link Vendors2form}.
 */
public interface Vendors2formService {

    /**
     * Creates a new Vendors2form. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vendors2form if any.
     *
     * @param vendors2form Details of the Vendors2form to be created; value cannot be null.
     * @return The newly created Vendors2form.
     */
	Vendors2form create(Vendors2form vendors2form);


	/**
	 * Returns Vendors2form by given id if exists.
	 *
	 * @param vendors2formId The id of the Vendors2form to get; value cannot be null.
	 * @return Vendors2form associated with the given vendors2formId.
     * @throws EntityNotFoundException If no Vendors2form is found.
	 */
	Vendors2form getById(Integer vendors2formId) throws EntityNotFoundException;

    /**
	 * Find and return the Vendors2form by given id if exists, returns null otherwise.
	 *
	 * @param vendors2formId The id of the Vendors2form to get; value cannot be null.
	 * @return Vendors2form associated with the given vendors2formId.
	 */
	Vendors2form findById(Integer vendors2formId);


	/**
	 * Updates the details of an existing Vendors2form. It replaces all fields of the existing Vendors2form with the given vendors2form.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Vendors2form if any.
     *
	 * @param vendors2form The details of the Vendors2form to be updated; value cannot be null.
	 * @return The updated Vendors2form.
	 * @throws EntityNotFoundException if no Vendors2form is found with given input.
	 */
	Vendors2form update(Vendors2form vendors2form) throws EntityNotFoundException;

    /**
	 * Deletes an existing Vendors2form with the given id.
	 *
	 * @param vendors2formId The id of the Vendors2form to be deleted; value cannot be null.
	 * @return The deleted Vendors2form.
	 * @throws EntityNotFoundException if no Vendors2form found with the given id.
	 */
	Vendors2form delete(Integer vendors2formId) throws EntityNotFoundException;

	/**
	 * Find all Vendors2forms matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vendors2forms.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Vendors2form> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Vendors2forms matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vendors2forms.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Vendors2form> findAll(String query, Pageable pageable);

    /**
	 * Exports all Vendors2forms matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Vendors2forms in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Vendors2form.
	 */
	long count(String query);


}

