/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SetModifiedDateForProjectRequest implements Serializable {

    @JsonProperty("DateModified")
    private Timestamp dateModified;
    @JsonProperty("project")
    private String project;

    public Timestamp getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(Timestamp dateModified) {
        this.dateModified = dateModified;
    }

    public String getProject() {
        return this.project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SetModifiedDateForProjectRequest)) return false;
        final SetModifiedDateForProjectRequest setModifiedDateForProjectRequest = (SetModifiedDateForProjectRequest) o;
        return Objects.equals(getDateModified(), setModifiedDateForProjectRequest.getDateModified()) &&
                Objects.equals(getProject(), setModifiedDateForProjectRequest.getProject());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDateModified(),
                getProject());
    }
}
