/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateFormStatusInMasterFormsRequest implements Serializable {

    @JsonProperty("formStatus")
    private Integer formStatus;
    @JsonProperty("closed")
    private Boolean closed;
    @JsonProperty("FormGUID")
    private String formGuid;

    public Integer getFormStatus() {
        return this.formStatus;
    }

    public void setFormStatus(Integer formStatus) {
        this.formStatus = formStatus;
    }

    public Boolean getClosed() {
        return this.closed;
    }

    public void setClosed(Boolean closed) {
        this.closed = closed;
    }

    public String getFormGuid() {
        return this.formGuid;
    }

    public void setFormGuid(String formGuid) {
        this.formGuid = formGuid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateFormStatusInMasterFormsRequest)) return false;
        final UpdateFormStatusInMasterFormsRequest updateFormStatusInMasterFormsRequest = (UpdateFormStatusInMasterFormsRequest) o;
        return Objects.equals(getFormStatus(), updateFormStatusInMasterFormsRequest.getFormStatus()) &&
                Objects.equals(getClosed(), updateFormStatusInMasterFormsRequest.getClosed()) &&
                Objects.equals(getFormGuid(), updateFormStatusInMasterFormsRequest.getFormGuid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFormStatus(),
                getClosed(),
                getFormGuid());
    }
}
