/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.civicxpress.letterservice.controller;
import com.civicxpress.letterservice.LetterService;
import java.lang.Long;
import java.lang.String;
import java.sql.SQLException;
import com.wavemaker.runtime.file.model.DownloadResponse;
import java.util.List;
import java.lang.Integer;
import com.civicxpress.letters.SectionalTemplatePdf;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController	
@RequestMapping(value = "/letter")
public class LetterController{

	@Autowired	
	private LetterService letterService;

	@RequestMapping(value = "/letter" ,  produces = "application/octet-stream", method = RequestMethod.POST )
	public DownloadResponse createLetter(@RequestParam(value="formTypeId", required=false)Long formTypeId, @RequestParam(value="formGuid", required=false)String formGuid, @RequestParam(value="letterTemplateId", required=false)int letterTemplateId )  throws  SQLException {
        
                return letterService.createLetter(formTypeId, formGuid, letterTemplateId);
	}

	@RequestMapping(value = "/availableTokens" , method = RequestMethod.GET )
	public List<String> getAvailableTokens(@RequestParam(value="formTypeId", required=false)int formTypeId )  throws  SQLException {
        
                return letterService.getAvailableTokens(formTypeId);
	}

	@RequestMapping(value = "/letterTemplate" , method = RequestMethod.GET )
	public SectionalTemplatePdf getLetterTemplate(@RequestParam(value="letterTemplateId", required=false)Integer letterTemplateId )  throws  SQLException {
        
                return letterService.getLetterTemplate(letterTemplateId);
	}

	@RequestMapping(value = "/letterTemplate" , method = RequestMethod.PUT )
	public void updateLetterTemplate(@RequestBody SectionalTemplatePdf letterTemplate, @RequestParam(value="formTypeId", required=false)Long formTypeId )  throws  SQLException {
         		    letterService.updateLetterTemplate(letterTemplate, formTypeId);
	}
} 