/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.civicxpress.gisrecordservice.controller;

import com.civicxpress.gisrecordservice.GisRecordService;
import org.springframework.web.multipart.MultipartFile;
import java.lang.Long;
import java.sql.SQLException;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/gisRecord")
public class GisRecordController {

    @Autowired
    private GisRecordService gisRecordService;

    @RequestMapping(value = "/uploadDocuments", method = RequestMethod.POST, consumes = "multipart/form-data")
    public void uploadDocuments(@RequestPart(value = "files") MultipartFile[] files, @RequestParam(value = "gisRecordId", required = false) Long gisRecordId) throws SQLException {
        gisRecordService.uploadDocuments(files, gisRecordId);
    }
}
