/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/



import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.civicxpress.cx2.SharedWith;
import com.civicxpress.cx2.service.SharedWithService;


/**
 * Controller object for domain model class SharedWith.
 * @see SharedWith
 */
@RestController("cx2.SharedWithController")
@Api(value = "SharedWithController", description = "Exposes APIs to work with SharedWith resource.")
@RequestMapping("/cx2/SharedWith")
public class SharedWithController {

    private static final Logger LOGGER = LoggerFactory.getLogger(SharedWithController.class);

    @Autowired
	@Qualifier("cx2.SharedWithService")
	private SharedWithService sharedWithService;

	@ApiOperation(value = "Creates a new SharedWith instance.")
	@RequestMapping(method = RequestMethod.POST)
        @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public SharedWith createSharedWith(@RequestBody SharedWith sharedWith) {
		LOGGER.debug("Create SharedWith with information: {}" , sharedWith);

		sharedWith = sharedWithService.create(sharedWith);
		LOGGER.debug("Created SharedWith with information: {}" , sharedWith);

	    return sharedWith;
	}


    @ApiOperation(value = "Returns the SharedWith instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SharedWith getSharedWith(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting SharedWith with id: {}" , id);

        SharedWith foundSharedWith = sharedWithService.getById(id);
        LOGGER.debug("SharedWith details with id: {}" , foundSharedWith);

        return foundSharedWith;
    }

    @ApiOperation(value = "Updates the SharedWith instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SharedWith editSharedWith(@PathVariable("id") Integer id, @RequestBody SharedWith sharedWith) throws EntityNotFoundException {
        LOGGER.debug("Editing SharedWith with id: {}" , sharedWith.getId());

        sharedWith.setId(id);
        sharedWith = sharedWithService.update(sharedWith);
        LOGGER.debug("SharedWith details with id: {}" , sharedWith);

        return sharedWith;
    }

    @ApiOperation(value = "Deletes the SharedWith instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteSharedWith(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting SharedWith with id: {}" , id);

        SharedWith deletedSharedWith = sharedWithService.delete(id);

        return deletedSharedWith != null;
    }

    /**
     * @deprecated Use {@link #findSharedWiths(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of SharedWith instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<SharedWith> searchSharedWithsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering SharedWiths list");
        return sharedWithService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the list of SharedWith instances matching the search criteria.")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<SharedWith> findSharedWiths(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering SharedWiths list");
        return sharedWithService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSharedWiths(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return sharedWithService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of SharedWith instances.")
	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countSharedWiths( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting SharedWiths");
		return sharedWithService.count(query);
	}


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service SharedWithService instance
	 */
	protected void setSharedWithService(SharedWithService service) {
		this.sharedWithService = service;
	}

}

