/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.civicxpress.cx2.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse implements Serializable {

    @ColumnAlias("content")
    private List<FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponseContent> content;

    public List<FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponseContent> getContent() {
        return this.content;
    }

    public void setContent(List<FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponseContent> content) {
        this.content = content;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse)) return false;
        final FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse fetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse = (FetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse) o;
        return Objects.equals(getContent(), fetchUnpaidFeesOfFormsForCreatedByAndSharedWithResponse.getContent());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContent());
    }
}
